default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root

development:
  <<: *default
  database: message_system_dev

test: &test
  <<: *default
  database: message_system_test
